// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_appsync_graphqlEndpoint': 'YOURENDPOING',
    'aws_appsync_region': 'YOURREGION',
    'aws_appsync_authenticationType': 'API_KEY',
    'aws_appsync_apiKey': 'YOURAPIKEY'
}

export default awsmobile;
